allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: true
  sharp: true
  workerd: true
  unrs-resolver: true
  '@parcel/watcher': true

minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20261009.1'
  - '@opennextjs/aws@4.1.9'
  - '@opennextjs/cloudflare@1.20.10'
  - miniflare@5.20261006.1-alpha
  - wrangler@4.149.0

overrides:
  postcss: 8.5.29
  "glob@>=10.2.0 <10.5.0": 10.5.0
  deepmerge-ts: ^8.0.0
  postcss-selector-parser: ^7.1.6
