import HealthCard from "@components/healthComponents/HealthCards";
import Layout from "@components/Layout";
import Head from "next/head";
import Image from "@components/ui/Image";

function health() {
  function scroll() {
    window.scrollTo({
      top: document.getElementById("knowMore")?.offsetLeft,
      behavior: "smooth",
    });
  }
  return (
    <Layout bgColor={"bg-[#7B61FF]"} headerBgLight={true} headerTextDark={true}>
      <Head>
        <title>Kilo y medio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="icon"
          href="/api/images/site/a28b33eb-a7b1-d7d9-0184-8ebb27a8f71c.ico"
        />
      </Head>

      <div>
        {/* Color Section */}
        <div className="h-screen w-full overflow-hidden bg-[#7B61FF]">
          <div className="mb-20 ml-6 mt-14 text-base-100 sm:ml-16 sm:mt-20 md:block lg:mt-32">
            <p className="font-raleway text-[36px] sm:text-xl lg:mr-44 lg:text-3xl">
              ¿SABÍAS QUE...
            </p>
            <p className="text-[28px] lg:mr-72 lg:text-[50px]">
              la gran mayoría de nuestros productos presentan beneficios
              saludables?
            </p>
          </div>
          <div className="flex justify-end">
            <Image
              src="/api/images/site/85babf23-e591-d4d7-4a03-e620fc2443cc.webp"
              width="700"
              height="400"
              alt="not found"
            />
          </div>
        </div>
        {/* End Color Section */}

        {/* 'saber más' Section */}
        <div className="bg-gradient-to-b from-[#7B61FF] to-base-content">
          <div className="relative z-0 mx-4">
            {/* Elipse */}
            <div className="absolute -top-[78px] left-0 flex w-full place-content-center px-[24px]">
              <Image
                src="/api/images/site/224c5a6b-f55e-e12d-03fa-e431df234b70.svg"
                alt="not found"
                className="-z-10 select-none"
                width={300}
                height={200}
                layout="fixed"
                objectFit="contain"
              />
              <p
                id="knowMore"
                onClick={scroll}
                className="absolute top-12 h-12 cursor-pointer select-none font-satoshiBold text-xs"
              >
                saber más
              </p>
            </div>
            {/* End Elipse */}
            <div className="rounded-box bg-base-100 px-4 pb-0.5 pt-14 text-xs text-base-content md:pt-28">
              <HealthCard
                name="LAS ALBÚMINAS..."
                subText="Son unos componentes que contienen las avellanas que
                    ayudan a nuestro organismo en la regeneración de tejido. Las
                    avellanas proporcionan energía a nuestro cuerpo y son muy
                    recomendadas para personas con problemas de colesterol."
                image="/api/images/site/29dc8dd0-a98e-4762-6a63-df2214cf2329.webp"
              />

              <HealthCard
                name="LAS ALMENDRAS, PISTACHOS Y NUECES..."
                subText="No solo ayudan a mejorar la memoria, sino que su consumo reduce los niveles de estrés de las personas."
                image="/api/images/site/9d500b07-9baa-3af7-d509-62573c52c7b2.webp"
              />

              <HealthCard
                name="EL APIO..."
                subText="Es un alimento carminativo, diurético, tranquilizante y depurativo. Es increíblemente saludable, pero, ¡cuidado! Si se padecen problemas graves de riñón, es mejor no consumirlo. Un buen consejo para que todos podamos disfrutar de sus propiedades, es reducir las sales cociendo el apio."
                image="/api/images/site/6eb85b8b-1d17-bcde-1957-41da5499f25f.webp"
              />
            </div>
          </div>
        </div>

        {/* End 'saber más' Section */}
      </div>
    </Layout>
  );
}
export default health;
