import { NextPage } from "next";
import { signIn, useSession, signOut } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";

const Login: NextPage = () => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Kilo y medio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        {session ? (
          <div className="grid gap-3 pt-3 mt-3 text-center">
            Signed in as <br />
            {session.user?.email}
            {session.user?.image && (
              <div>
                <Image
                  src={session.user.image}
                  alt="avatar"
                  width="100px"
                  height="100px"
                  layout="fixed"
                />
              </div>
            )}
            <button
              className="bg-gray-800 rounded-md text-red-100 p-3"
              onClick={() => signOut()}
            >
              Sign out
            </button>
          </div>
        ) : (
          <div className="grid gap-3 pt-3 mt-3 text-center">
            <button
              className="bg-red-500 rounded-md text-red-100 p-3"
              onClick={() => signIn("google")}
            >
              Sign in
            </button>
          </div>
        )}
      </main>
    </>
  );
};

export default Login;
