import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useCallback } from "react";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import { trpc } from "../utils/trpc";
import { ISignUp, signUpSchema } from "../utils/validations/auth";

const SignUp: NextPage = () => {
  const router = useRouter();
  const { register, handleSubmit } = useForm<ISignUp>({
    resolver: zodResolver(signUpSchema),
  });

  const { mutateAsync } = trpc.useMutation(["user.createNewClient"]);

  const onSubmit = useCallback(
    async (data: ISignUp) => {
      const result = await mutateAsync(data);
      if (result.status === 201) {
        router.push("/");
      }
    },
    [mutateAsync, router],
  );

  return (
    <div>
      <Head>
        <title>Next App - Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center">
        <form
          className="flex items-center justify-center h-screen w-full max-w-sm"
          onSubmit={handleSubmit(onSubmit)}
        >
          <div className="m-64">
            <div className="shadow-xl p-12">
              <h2 className="font-bold mb-6 text-xl text-blue-500 ml-6 cursor-default text-center">
                Create an account!
              </h2>
              <div className=" m-6">
                <input
                  type="text"
                  placeholder="Type your username..."
                  className="bg-gray-100 mb-4 py-1 px-8 border-l-4 border-l-blue-500"
                  {...register("username")}
                />
                <input
                  type="email"
                  placeholder="Type your email..."
                  className="bg-gray-100 mb-4 py-1 px-8 border-l-4 border-l-blue-500"
                  {...register("email")}
                />
                <input
                  type="password"
                  placeholder="Type your password..."
                  className="bg-gray-100 mb-2 py-1 px-8 border-l-4 border-l-blue-500"
                  {...register("password")}
                />
              </div>
              <div className="flex justify-center items-center">
                <div className="m-auto text-center">
                  <Link href="/">
                    <p className=" font-semibold  text-gray-600 cursor-pointer">
                      Go to login
                    </p>
                  </Link>
                  <button
                    className="block bg-blue-500 pl-20 pr-20 py-1 mt-3 text-white font-semibold m-2 rounded"
                    type="submit"
                  >
                    Sign Up
                  </button>
                </div>
              </div>
            </div>
          </div>
        </form>
      </main>
    </div>
  );
};

export default SignUp;
