import { NextPage } from "next";
import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

const Login: NextPage = () => {
  const { data: session } = useSession();
  const nextRouter = useRouter();

  return (
    <>
      <Head>
        <title>Kilo y medio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        {session ? (
          <div className="mt-3 grid gap-3 pt-3 text-center">
            Signed in as <br />
            {session.user?.email}
            {session.user?.image && (
              <div>
                <Image
                  src={session.user.image}
                  alt="avatar"
                  width="100px"
                  height="100px"
                  layout="fixed"
                />
              </div>
            )}
            <button
              className="rounded-md bg-gray-800 p-3 text-red-100"
              onClick={() => signOut()}
            >
              Sign out
            </button>
          </div>
        ) : (
          <div className="mt-3 grid gap-3 pt-3 text-center">
            <button
              className="rounded-md bg-button p-3 text-red-100"
              onClick={() => nextRouter.push("/login")}
            >
              Sign in
            </button>
          </div>
        )}
      </main>
    </>
  );
};

export default Login;
