import { NextPage } from "next";
import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "@components/ui/Image";
import { useRouter } from "next/router";

const Login: NextPage = () => {
  const { data: session } = useSession();
  const nextRouter = useRouter();

  return (
    <>
      <Head>
        <title>Kilo y medio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="icon"
          href="/api/images/site/a28b33eb-a7b1-d7d9-0184-8ebb27a8f71c.ico"
        />
      </Head>
      <main className="min-h-screen container mx-auto flex flex-col items-center justify-center p-4">
        {session ? (
          <div className="mt-3 grid gap-3 pt-3 text-center">
            Signed in as <br />
            {session.user?.email}
            {session.user?.image && (
              <div>
                <Image
                  src={session.user.image}
                  alt="avatar"
                  width={100}
                  height={100}
                  layout="fixed"
                />
              </div>
            )}
            <button
              className="rounded-md bg-gray-800 p-3 text-red-100"
              onClick={() => signOut()}
            >
              Sign out
            </button>
          </div>
        ) : (
          <div className="mt-3 grid gap-3 pt-3 text-center">
            <button
              className="btn-sm rounded-md p-3 text-red-100"
              onClick={() => nextRouter.push("/login")}
            >
              Sign in
            </button>
          </div>
        )}
      </main>
    </>
  );
};

export default Login;
