name: Jest
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: http://localhost:3001
      NEXTAUTH_SECRET: 0
      NEXTAUTH_URL: http://localhost:3000/
      GOOGLE_CLIENT_ID: ""
      GOOGLE_CLIENT_SECRET: ""
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Run Playwright tests
        run: yarn test
